CXX = g++
CXXFLAGS = -Wall -O2 -DNDEBUG -Isrc
LDFLAGS = -lutil

TARGET = lite-tty-ime
SRC = src/tui_shell.cpp src/util.cpp src/status_bar.cpp \
      src/pinyin_data.cpp src/pinyin_file_io.cpp src/pinyin_split.cpp src/pinyin_matcher.cpp \
      src/pinyin_composition.cpp src/word_matcher.cpp src/candidate_item.cpp \
      src/pinyin_virtual_cursor.cpp src/ime_controller.cpp

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET) $(LDFLAGS)

clean:
	rm -f $(TARGET)

.PHONY: clean
